In [1]:
import numpy as np 

arr = np.random.randint(1,11,size=(5,5))
arr

array([[ 5,  1,  7,  9,  5],
       [ 9,  7, 10,  3,  5],
       [ 7,  8,  3,  3,  8],
       [10, 10,  1,  8,  7],
       [ 8, 10,  1,  1,  4]], dtype=int32)

# filtering 


In [4]:
arr[arr>5]
print(arr[arr > 5 ])

[ 7  9  9  7 10  7  8  8 10 10  8  7  8 10]


In [5]:
# Filter elements that are both greather than 5 and even

print(arr[(arr%2==0) & (arr > 4)])

[10  8  8 10 10  8  8 10]


In [ ]:
print(arr)
arr1 = np.array([True, False, True,False,True])
# only show  the rows where true condition is there 
print(arr[arr1])

# Filtering based on indexing in 2d Array

In [9]:
print(arr)
filterr =  arr[2][arr[2,:] > 5]
print("*" * 40)
print(filterr)

[[ 5  1  7  9  5]
 [ 9  7 10  3  5]
 [ 7  8  3  3  8]
 [10 10  1  8  7]
 [ 8 10  1  1  4]]
****************************************
[7 8 8]


# aggregate functions 

In [13]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))

print(np.sum(arr, axis = 0)) # cols 
print(np.sum(arr, axis = 1))


15
21
[5 7 9]
[ 6 15]


In [14]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))
     

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


In [15]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [16]:

arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

1
1
[1 2 3]
[1 4]
--------------------
5
6
[4 5 6]
[3 6]
