In [15]:
import numpy as np 

arr = np.array([1,2,3,None, 4,5,None])
print(arr)

arr[arr == None] = np.nan # assign NAN to a none value
# print(arr)


print(None)
print(np.nan)





[1 2 3 None 4 5 None]
None
nan


# Removing null values from array

In [16]:

arr = np.array([1,2,3,np.nan, 4,5,np.nan])

print(np.isnan(arr))
print(~np.isnan(arr))

arr = arr[~np.isnan(arr)]
print(arr)

[False False False  True False False  True]
[ True  True  True False  True  True False]
[1. 2. 3. 4. 5.]


# Removing the NULL values 

In [18]:
arr = np.array([1,2,3,np.nan, 4,5,np.nan])
print(np.isnan(arr))
print(~np.isnan(arr))

arr[np.isnan(arr)] = 0
print(arr)


[False False False  True False False  True]
[ True  True  True False  True  True False]
[1. 2. 3. 0. 4. 5. 0.]


# Filling NULL with average values 

In [23]:
arr = np.array([21,22,22, np.nan, 24,25,np.nan])
# print(arr)
# print(arr[np.isnan(arr)]) # gives null values 

arr[np.isnan(arr)] = int(np.nanmean(arr))
print(arr)


[21. 22. 22. 22. 24. 25. 22.]
