In [7]:
import numpy as np

# Generating a random array of 100 integers between 1 and 100
arr = np.random.randint(low=1, high=101, size=100)

# print(arr)

mean = np.mean(arr)
median = np.median(arr)

# Computing variance and standard deviation
variance = np.var(arr)
std_dev = np.std(arr)

print('-'*20)
# Computing quartiles (Q1, Q2, Q3) and interquartile range (IQR)
q1 = np.percentile(arr, 25)
q2 = np.percentile(arr, 50)  # Median ===  50th percentile
q3 = np.percentile(arr, 75)
iqr = q3 - q1
# print(iqr)

# Skewness measures the asymmetry of the distribution of a dataset.
# A positive skew means the distribution has a longer tail on the right side.
# A negative skew means the distribution has a longer tail on the left side.
# A skewness of 0 indicates a perfectly symmetrical distribution
skewness = np.mean((arr - mean) ** 3) / (std_dev ** 3)


kurtosis = np.mean((arr - mean) ** 4) / (std_dev ** 4)

# Kurtosis measures the "tailedness" or the sharpness of the peak of the distribution.
# A high kurtosis indicates that the distribution has heavy tails and a sharper peak (i.e., more outliers).
# A low kurtosis indicates that the distribution has lighter tails and a flatter peak




print('Mean      : ', mean)
print('Median    : ', median)
# print('Mode      : ', mode)
print('-'*20)

print('Variance  : ', variance)
print('Standard  : ', std_dev)
print('-'*20)

print('Q1        : ', q1)
print('Q2        : ', q2)
print('Q3        : ', q3)
print('-'*20)

print('IQR       : ', iqr)
print('Skewness  : ', skewness)
print('Kurtosis  : ', kurtosis)

--------------------
Mean      :  45.14
Median    :  45.5
--------------------
Variance  :  813.4204
Standard  :  28.52052594185458
--------------------
Q1        :  19.5
Q2        :  45.5
Q3        :  67.0
--------------------
IQR       :  47.5
Skewness  :  0.15023638963047772
Kurtosis  :  1.8498599222767877


# Searching and shorting in python 

In [13]:
import numpy as np
arr = np.array([1,3,4,6,5,7,12,13])
print(np.where(arr==3))
index=  np.where(arr==3)[0]
print(index)


#  to find the element in the array that is closest to a given value.
arr = np.array([1,3,4,6,5,7,12,13])
index = np.argmin(abs(arr - 11))
print(index)

# binary search 
index = np.searchsorted(arr, 6)
print(index)

arr = np.array([5,7,9,0,3,1,6,2,4,8])

# Quick Sort
sorted_arr = np.sort(arr)
sorted_arr = np.sort(arr, kind = 'quicksort')
# print(sorted_arr)

# Heap Sort
sorted_arr = np.sort(arr, kind = 'heapsort')
# print(sorted_arr)

# Merge Sort
sorted_arr = np.sort(arr, kind = 'mergesort')
# print(sorted_arr)

(array([1]),)
[1]
6
5


In [19]:
arr = np.array([1,2,np.nan,4,5,np.nan])
print(arr)

print(np.isnan(arr))


print(arr[np.isnan(arr)])

arr[arr > 7] = 7


arr = np.array([1,2,2,2,3,3,4,5,6,7,8,9])
print(arr)

unique_arr = np.unique(arr)
print(unique_arr)
print(set(arr))


[ 1.  2. nan  4.  5. nan]
[False False  True False False  True]
[nan nan]
[1 2 2 2 3 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
{np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)}


# Data cleaning 

# categorical data to One hot encoding 

In [22]:
categorical_arr = np.array(['A', 'B', 'C', 'D', 'E'])
numrical_arr = np.array([0, 1, 2, 3, 4])
# 'A' is at position 0
# 'B' is at position 1
# 'C' is at position 2
# 'D' is at position 3
# 'E' is at position 4
one_hot_arr = np.eye(5)[numrical_arr]
print(one_hot_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# data normalization

In [25]:
arr = np.array([10000,200000,300000,4000000,5000000])
  
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)
#  all values will now come between 0 and 1
# 
# 

[0.         0.03807615 0.05811623 0.7995992  1.        ]
