In [11]:
#numpy
import numpy as np 

lst = [1,2,3,4,5]
arr = np.array(lst,ndmin=1)
print(type(arr))
print(arr)
 

<class 'numpy.ndarray'>
[1 2 3 4 5]


# Arrange function
The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop) 

In [8]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

3. Multidimensional Array + Size function


In [25]:
marr = np.array([[1,2,3],[4,5,6]])
print(marr)

print("Total: ",marr.size)
print("Rows :", np.size(marr,0))
print("Cols :", np.size(marr,1))
print("ARRshape", marr.shape)

[[1 2 3]
 [4 5 6]]
Total:  6
Rows : 2
Cols : 3
ARRshape (2, 3)


# Dtype Function
Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array. This means it gives us information about:

Type of the data (integer, float, Python object, etc.)
Size of the data (number of bytes)
The byte order of the data (little-endian or big-endian)
If the data type is a sub-array, what is its shape and data type?

In [44]:
print(marr.dtype)

int64


# Ndim function
> no of dimensions

In [42]:
print(marr.ndim) # prints no of dimensions

2


In [43]:

arr1 = np.array([1,2,3,1,2,3])
print(arr1)
arr3 = np.array(arr1, ndmin = 3)
print(arr3.ndim)
print(arr3)



[1 2 3 1 2 3]
3
[[[1 2 3 1 2 3]]]


# Zeros  Function + Ones Function 
> The numpy.zeros() function returns a new array of given shape and type, with zeros. Syntax:

> numpy.zeros(shape, dtype = None)

In [54]:
arr1 = np.zeros(shape=(2,3) , dtype = float)
print(arr1)

print("-"*10)
arr1 = np.ones(shape=(2,3) , dtype = int)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
----------
[[1 1 1]
 [1 1 1]]


# 9. Eye  Function
The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k.

In [55]:
#  generating a identity matrix 

print(np.eye(4, dtype = 'int'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Empty  Function
Return am empty array of given shape and type

In [61]:
np.empty(shape = (2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.42420345e-306]])

# Random  Functions
a) np.random.rand /
The numpy.random.rand() function creates an array of specified shape and fills it with random values.

In [ ]:
np.random.rand(2,3)

# intiializes values iwthing range 
np.random.randint(low=1,high=15,size=10)

np.random.randn(1000)
#The function np.random.randn(1000) generates 1000 random numbers that 
# are drawn from a standard normal distribution 
# (also known as a Gaussian distribution) with a mean of 0 and a 
# standard deviation of 1.



array([-9.37886077e-01,  2.53297569e+00,  8.20037125e-01,  2.31792932e-01,
       -1.97472335e+00,  7.15695264e-01,  8.78387182e-01,  6.88714947e-01,
       -3.10562716e-01, -3.67924881e-02, -2.79640718e-01, -2.68881628e-01,
       -1.52314007e+00, -1.75187767e+00,  8.50172426e-01,  5.70750287e-01,
        1.97442570e+00,  3.74834477e-01,  1.78340913e-01, -2.24283939e+00,
       -1.39167180e+00, -5.05325197e-02,  1.93009329e+00, -4.95943463e-02,
        6.15650712e-01, -3.28132197e-01, -2.35794396e+00, -2.59124552e-02,
        4.17887382e-01,  3.66241023e-01,  5.65334541e-01,  6.26774800e-01,
        1.18637370e+00,  9.77402657e-01,  6.45475715e-01, -2.36333718e+00,
        8.52513272e-01, -2.00038599e-01, -1.80997671e+00, -5.71714555e-01,
        1.22053052e+00,  1.30561041e+00, -1.14993795e-01,  4.66756807e-01,
        6.12336603e-02,  9.97771758e-01, -9.49518558e-01,  1.69892410e-01,
       -5.79516549e-01, -1.19040312e+00, -3.84120645e-01,  6.02235560e-01,
       -8.61015573e-01,  

# Reshaping the array 


In [74]:
arr  = np.random.randint(1,15,size = (3,4))
print(arr.size)
print(arr)
print("*"*10)
arr2 = arr.reshape(4,3)
print(arr2.size)
print(arr2)

12
[[ 8  4  3  3]
 [ 8 14  9  5]
 [ 7  7  2 12]]
**********
12
[[ 8  4  3]
 [ 3  8 14]
 [ 9  5  7]
 [ 7  2 12]]


# Linspace  Function
The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [79]:
np.linspace(start=1, stop=10, num=50, endpoint=True, retstep=False, dtype='int', axis=0)

#start=1: The sequence starts at 1.
# stop=10: The sequence ends at 10 (inclusive because endpoint=True).
# num=50: This specifies that 50 values should be generated in the sequence.
# endpoint=True: The stop value (10) is included in the sequence.
# retstep=False: This means that the step size (distance between consecutive values) will not be returned.
# dtype='int': The values in the resulting array are converted to integers. Since the default behavior of np.linspace generates floating-point numbers, specifying dtype='int' will round or truncate the generated numbers to integers.
# axis=0: The sequence will be generated along the first axis of the array (which is the default behavior and doesn't change the result here).

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

# Flatten

In [87]:
arr = np.random.randint(1,10,size=(2,3))
print(arr.shape)
print(arr)
print('*' * 19 , "after flatenning")
flatttt =  arr.flatten()
print(flatttt)
print(flatttt.shape)

(2, 3)
[[9 8 3]
 [1 3 4]]
******************* after flatenning
[9 8 3 1 3 4]
(6,)


# Logspace 
same as linspace but with log 

In [90]:
print(np.logspace(1,10,base = 3,dtype=int))

[    3     3     4     5     6     8    10    12    15    18    22    27
    33    41    50    61    75    92   113   138   169   207   254   310
   380   465   569   697   852  1043  1276  1562  1911  2339  2862  3502
  4285  5243  6415  7849  9605 11752 14380 17595 21529 26343 32233 39440
 48258 59049]


# . Copy function
If we normally use the equals sign then the **id** of both the numpy array will be same, so we need to use to copy function

In [91]:
arr1 = np.random.randint(1,15,10)

arr2 = arr1

print("here both the ids are same ")
print(arr1, id(arr1))
print(arr2, id(arr2))

print("*"*7)
arr2  = np.copy(arr1)
print("here both the ids are diff ")
print(arr1, id(arr1))
print(arr2, id(arr2))


here both the ids are same 
[ 5  8 12  2  5  5  3  2 14 13] 2510384932656
[ 5  8 12  2  5  5  3  2 14 13] 2510384932656
*******
here both the ids are diff 
[ 5  8 12  2  5  5  3  2 14 13] 2510384932656
[ 5  8 12  2  5  5  3  2 14 13] 2510384515280


# arr.max() ,  arr.min() ,     arr.sum() functions


We can use the axis parameter to get the max, min and sum of a particular column or row

axis=0 is for the column
axis=1 is for the row

In [99]:
arr  = np.random.randint(1,10,(2,4))
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr)
print("max of a col (axix= 0)")
print(arr.sum(axis=0))

9
1
41
[[8 2 9 6]
 [7 1 1 7]]
max of a col (axix= 0)
[15  3 10 13]


# Seed Function
random() function is used to generate random numbers in Python. Not actually random, rather this is used to generate pseudo-random numbers. That implies that these randomly generated numbers can be determined. random() function generates numbers for some values. This value is also called seed value.

In [117]:
np.random.seed(3)
print("random array(seed value) ")
arr = np.random.randint(1,10,(2,3))
print(arr)  # this wont change values 




random array(seed value ) 
[[9 4 9]
 [9 1 6]]
******
random array 
[[4 6 8]
 [7 1 5]]


In [125]:
#but this wil generate random values everytime 
print("*"*6)
print("random array ")
arr2 = np.random.randint(1,10,(2,3))
print(arr2)

******
random array 
[[1 1 3]
 [3 8 1]]


# Sorting Function
numpy.sort() : This function returns a sorted copy of an array.

Parameters :

arr : Array to be sorted.
axis : Axis along which we need array to be started.
order : This argument specifies which fields to compare first.
kind : [‘quicksort’{default}, ‘mergesort’, ‘heapsort’]Sorting algorithm

In [152]:
arr2 = np.random.randint(1,10,(3,3))
print(arr2)
# arr2.sort(axis =1 ) # row wise
# arr2

arr2.sort(axis= 0)
arr2  # col wiser

print("*"*6)

arr2.sort(kind='mergesort')
print(arr2)



[[8 1 5]
 [3 9 9]
 [3 9 9]]
******
[[1 3 5]
 [3 9 9]
 [8 9 9]]


# array operationss 


In [153]:
np.random.seed(3)
print("random array(seed value) ")
arr = np.random.randint(1,10,(2,3))
print(arr)    
print("*"*6)

#addition (adds to all values of array)
print(arr+1)

 


random array(seed value) 
[[9 4 9]
 [9 1 6]]
******
[[10  5 10]
 [10  2  7]]


# Matrix multiplication 

In [156]:
np.random.seed(3)
print("random array(seed value) ")
arr1 = np.random.randint(1,10,(2,2))
arr2 = np.random.randint(1,10,(2,2))
print(arr1)    
print(arr2)
print("*"*6,"printing dot product ")
 
# for matrix multiplication 
arr1.dot(arr2)



print(arr1**2)


random array(seed value) 
[[9 4]
 [9 9]]
[[1 6]
 [4 6]]
****** printing dot product 
[[81 16]
 [81 81]]
