In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# creating  2darray from  a list of arrays

In [7]:
arr = np.array([np.array([1,2,3]),np.array([4,5,6])])
print(arr)


[[1 2 3]
 [4 5 6]]
