# Array VS List comparison 


In [9]:
import numpy as np
lst =[1,2,3,4]
print(lst)

arr = np.array([1,2,4,4])
print(arr)
print(type(lst))
print(type(arr))
print(lst == arr)
print(arr.tolist() == lst)

[1, 2, 3, 4]
[1 2 4 4]
<class 'list'>
<class 'numpy.ndarray'>
[ True  True False  True]
False


# Adding elements in an Array vs List

In [10]:
arr = np.array([1,2,3])
print(arr)
arr= np.append(arr,99)
print(arr)

[1 2 3]
[ 1  2  3 99]


# Removing elements in array VS List 

In [15]:
arr = np.array([1,2,3])
print(arr)
arr = np.delete(arr,0)
print(arr)

[1 2 3]
[2 3]


# Updating elements in array VS List 

In [16]:
arr = np.array([1,2,3])
print(arr)
arr = np.array([1,2,3,4])
print(arr)

[1 2 3]
[1 2 3 4]


# Array VS List Comparison

In [17]:
import time

# Creating the data
my_list = list(range(10000000))
my_array = np.arange(10000000)

# Search time for list
start_time = time.time()
for _ in range(100):
  if 5000000 in my_list:
    pass
end_time = time.time()
print('List : ', end_time - start_time)


# Search time for Array
start_time = time.time()
for _ in range(100):
  if 5000000 in my_array:
    pass
end_time = time.time()
print('Array : ', end_time - start_time)

List :  2.519253730773926
Array :  0.8863210678100586


# 1. Converting Data Structures to Numpy Array

In [19]:
tpl = (1,2,3)
print(tpl)
print(type(tpl))
print('-'*10)

arr = np.array(tpl)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
----------
[1 2 3]
<class 'numpy.ndarray'>


# Converting a list to an array

In [20]:

lst = [1,2,3]
print(lst)
print(type(lst))
print('-'*10)

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>


# Converting a dictionary to an array

In [21]:
dict = {1:"mango",2:'apple',3:"banana"}
arr_k = np.array([dict.keys()])
arr_v = np.array([dict.values()])
print(arr_k) 
print(arr_v)

[dict_keys([1, 2, 3])]
[dict_values(['mango', 'apple', 'banana'])]


# Converting a set to an array

In [23]:
set_ = {1,2,3}
print(set_)

arr = np.array(set_)
arr1 = np.array(list(set_))
print(arr)
print(arr1)
print(type(arr))

{1, 2, 3}
{1, 2, 3}
[1 2 3]
<class 'numpy.ndarray'>


# Converting a string to a array 

In [6]:
import numpy as np
arr  =np.array('hello word')
print(arr)
print(type(arr))
arr = np.array(list('hello word'))
print(type(arr))
print(arr)

hello word
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'd']


# 2. Convering the Datatype of Numpy Array

In [32]:
arr = np.array([1,2,3,4])
arr = arr.astype('float')
print(arr)
arr = arr.astype('str')
print(arr)
arr = arr.astype('bool')
print(arr)
#  similary for remaining types and viceversa 

[1. 2. 3. 4.]
['1.0' '2.0' '3.0' '4.0']
[ True  True  True  True]
