In [1]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.txt',arr)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.save('data1.npy', arr)

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.savetxt('data2.csv',arr3,delimiter=',',header='a,b,c')

arr = np.array([[1,2,3],[4,5,6]])

np.savetxt('data.yaml',arr, delimiter = ',', header = '- data : ')

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.json',arr, delimiter = ',', header = '{"data"  : [', footer = ']}')

In [6]:
import numpy as np 

data = np.loadtxt('data.txt')
print(data)


data = np.loadtxt('data2.csv',delimiter=',')
print(data)


data = np.loadtxt('data.json',delimiter=',')
print(data)



data = np.loadtxt('data.yaml', delimiter = ',')

print(data)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


# Replacing existing content

In [19]:
import numpy as np
data = np.array([1,2,3])
np.savetxt('data-1.txt', data, delimiter = ',')

data = np.array([4,5,6])
np.savetxt('data-2.txt', data, delimiter = ',')

# Appending data on existing file 

In [28]:
import numpy as np
data = np.load('data1.npy',allow_pickle=True)
# np.savetxt('data11.txt', data, delimiter = ',')
print(data)
np.save('new_data.npy', data)

[[1 2 3]
 [4 5 6]]
